config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :articles
  resources :sessions, only: [:new, :create, :destroy]

  root 'welcome#index'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true,
                  length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :admin_user

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
   
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
   def destroy
    @article = Article.find(params[:id])
    @article.destroy
   
    redirect_to articles_path
  end
  
  private

    def article_params
      params.require(:article).permit(:title, :text)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :show]
  before_action :correct_user,   only: [:edit, :update, :show]
  before_action :admin_user,     only: [:index, :destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sangha!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update 
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    def signed_in_user
      unless signed_in?
        flash[:warning] = "Please sign in."
        store_location
        redirect_to signin_path
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.order("created_at desc").limit(1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def phone_number_link(text)
    sets_of_numbers = text.scan(/[0-9]+/)
    number = "+1-#{sets_of_numbers.join('-')}"
    link_to text, "tel:#{number}"
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def phone_number_link(text)
    sets_of_numbers = text.scan(/[0-9]+/)
    number = "+1-#{sets_of_numbers.join('-')}"
    link_to text, "tel:#{number}"
  end
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The article was not saved because of <%= pluralize(@article.errors.count, "error") %>.
    </div> 
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
  <fieldset>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title, size: 40 %>
    </p>
   
    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text, :class => "tinymce", cols: 50, rows: 15 %>
    </p>
   
    <p>
      <%= f.submit %>
    </p>
  </fieldset>
<% end %>
<%= tinymce %>

app/views/articles/edit.html.erb
<%= link_to 'Back', articles_path %>
  
  <legend>Edit Article</legend>

  <%= render 'form' %>
 

app/views/articles/index.html.erb
<% provide(:title, 'Article Index') %>
<%= link_to 'Home', controller: 'welcome' %>
<div class="row">
  <div class="col-md-8">
    <h1>Listing articles<small><%= link_to ' New article', new_article_path %></small></h1>    
  </div>
</div>

<div class="row">
<% @articles.each do |article| %>
  <div class="col-md-6">
    <h2><%= article.title %></h2>
    <ul class="list-inline">
      <li><%= link_to 'Show', article_path(article) %></li>
      <li><%= link_to 'Edit', edit_article_path(article) %></li>
      <li><%= link_to 'Destroy', article_path(article),
              method: :delete, data: { confirm: 'Are you sure?' } %></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-10">
    <%= simple_format(article.text.html_safe) %> 
  </div> 
<% end %>
</div>

app/views/articles/new.html.erb
<% provide(:title, 'New Article') %>
<%= link_to 'Back', articles_path %>

  <legend>New Article</legend>

    <%= render 'form' %>

app/views/articles/show.html.erb
<% provide(:title, 'Preview Article') %>
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= simple_format(@article.text.html_safe) %>
</p>

<%= link_to 'Back', articles_path %>
| <%= link_to 'Edit', edit_article_path(@article) %>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class = "container">
    <nav class="pull-right">
      <ul class="list-inline">
        <li><%= link_to "Home", root_path %></li>
      </ul>
    </nav>
    <address>
      <p>For more information:</p> 
      <p>Email: <%= mail_to 'kagyudc@gmail.com' %></p>
      <p>Telephone: <%= phone_number_link("(202) 546-0226") %></p>
      1519 D St., SE <br />
      Washington, DC 20003
    </address>
  </div>
</div>

app/views/layouts/_header.html.erb
    <div id="fadeMenu">
      <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <%= link_to 'KagyuDC', { :controller => 'welcome' }, { :class=> 'navbar-brand' } %>

          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">

                <%= render 'layouts/nav_items' %>


              <% if signed_in? %>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                  Account <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
                  <% if current_user.admin? %>
                    <li class="divider"></li>
                    <li role="presentation" class="dropdown-header">Admin Menu</li>
                    <li><%= link_to "Articles", controller: 'articles' %></li>
                    <li><%= link_to "Users", users_path %></li>
                  <% end %>
                </ul>
              </li>
              <% else %>
              <!-- <li><%#= link_to "Sign in", signin_path %></li> -->
            <% end %>
          </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
<div class="container"> 
  <header class="text-center">
<h1><%= link_to 'Kagyu Drupgyu Chodzong', root_path, class: "pull-left" %></h1>
        <ul class="list-inline pull-right">

          <%= render 'layouts/nav_items' %>
        </ul>        
        <%= image_tag "lotus.png", :size => "75", :class => "img-responsive" %>
        
        <p class="lead">A Tibetan Buddhist community in Washington, DC under the guidance of Lama Norlha Rinpoche</p>

  </header>
</div>

app/views/layouts/_nav_items.html.erb
<li><%= link_to "Our Teachers", about_path(anchor: "teachers") %></li>
<li><%= link_to "Weekly Practice", root_path(anchor: "practice") %></li>
<li><%= link_to "Dharma Center", about_path(anchor: "center") %>
<li><%= link_to "Kagyu Lineage", about_path(anchor: "lineage") %></li>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="A Tibetan Buddhist community in Washington, DC 
                                    under the guidance of Lama Norlha Rinpoche">
  <meta name="author" content="Ken Crocken">

  <title>KagyuDC | <%= yield(:title) %></title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>

  <%= render 'layouts/shim' %>

</head>
<body>

<%= render 'layouts/header' %>
<div class = "container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

    <%= yield %>

  <%= render 'layouts/footer' %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<div class="row">
  <div class="col-md-7 col-md-offset-2">
    <h2>About Us</h2>
    <p>Find me in app/views/static_pages/about.html.erb</p>

    <p>Lorem ipsum dolor sit amet, sit an legimus petentium, ex vidit iudicabit efficiendi vix, etiam veritus ne usu. Putent possit inciderint nec no. Ei sit homero facete phaedrum, ex illud justo cotidieque vis. Ei quo legere sententiae, ad sit vitae oportere. Ei his brute nihil. Mea te unum vivendum. Usu ex tantas laoreet interesset, vocent scripta eos no, ea mei oratio munere aperiri.</p>

    <p>Vel vocibus torquatos eu, at sea minim viderer. Vel eu novum animal, est an dicam consul. Accusata deseruisse no pri, ferri fugit mucius ut cum. Option detracto iudicabit cu vis. Nostro postulant adolescens at sit.</p>

    <p>Ei eum graeci accumsan constituto. Ne ius fastidii imperdiet assueverit, eius partem singulis mel id. Ius elitr option eu, iriure appetere vis ut. Et mei mucius commodo explicari, vis dolorem civibus sententiae an.</p>

    <p>Atqui ocurreret reprimique cu mei, eam eu case volutpat maluisset, an sint eros quo. Ius homero detraxit phaedrum an. Sed modus prodesset ad, ne eam alii exerci detracto. Iudico voluptua mnesarchum ut vel, fuisset vivendum vel an. Mei mutat quando lobortis eu, reque corpora complectitur cu mei, ei his fuisset contentiones. Pri an meliore consequat, sit enim saepe in, eam mediocrem referrentur ex.</p>

    <p>Sed quidam possit et, dolor perpetua in sed. Eu habeo impedit mea. Ex qui nibh latine, pro esse intellegat at. Mea ludus vidisse ea, ius facilisi sapientem ex. In phaedrum sapientem est. Ea aperiam feugait nominavi qui, iisque scripta definitiones vix ut, vix erant omnes viderer et.</p>
  </div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<div class="row">
  <div class="col-md-7 col-md-offset-2">
    <h2>Contact Us</h2>
    <p>Find me in app/views/static_pages/contact.html.erb</p>

    <p>Lorem ipsum dolor sit amet, sit an legimus petentium, ex vidit iudicabit efficiendi vix, etiam veritus ne usu. Putent possit inciderint nec no. Ei sit homero facete phaedrum, ex illud justo cotidieque vis. Ei quo legere sententiae, ad sit vitae oportere. Ei his brute nihil. Mea te unum vivendum. Usu ex tantas laoreet interesset, vocent scripta eos no, ea mei oratio munere aperiri.</p>

    <p>Vel vocibus torquatos eu, at sea minim viderer. Vel eu novum animal, est an dicam consul. Accusata deseruisse no pri, ferri fugit mucius ut cum. Option detracto iudicabit cu vis. Nostro postulant adolescens at sit.</p>

    <p>Ei eum graeci accumsan constituto. Ne ius fastidii imperdiet assueverit, eius partem singulis mel id. Ius elitr option eu, iriure appetere vis ut. Et mei mucius commodo explicari, vis dolorem civibus sententiae an.</p>

    <p>Atqui ocurreret reprimique cu mei, eam eu case volutpat maluisset, an sint eros quo. Ius homero detraxit phaedrum an. Sed modus prodesset ad, ne eam alii exerci detracto. Iudico voluptua mnesarchum ut vel, fuisset vivendum vel an. Mei mutat quando lobortis eu, reque corpora complectitur cu mei, ei his fuisset contentiones. Pri an meliore consequat, sit enim saepe in, eam mediocrem referrentur ex.</p>

    <p>Sed quidam possit et, dolor perpetua in sed. Eu habeo impedit mea. Ex qui nibh latine, pro esse intellegat at. Mea ludus vidisse ea, ius facilisi sapientem ex. In phaedrum sapientem est. Ea aperiam feugait nominavi qui, iisque scripta definitiones vix ut, vix erant omnes viderer et.</p>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h2 class="text-center">Update your profile</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

          <%= f.label :name, class: "control-label" %>
          <%= f.text_field :name, :placeholder => " Enter your full name", 
                                      class: "form-control" %>

          <%= f.label :email, class: "control-label" %>
          <%= f.text_field :email, :placeholder => " Enter your email address", 
                                      class: "form-control" %>

          <%= f.label :password, class: "control-label" %>
          <%= f.password_field :password, :placeholder => " Enter your Password", 
                                      class: "form-control" %>

          <%= f.label :password_confirmation, "Confirmation", class: "control-label" %>
          <%= f.password_field :password_confirmation, :placeholder => " Confirm password", 
                                      class: "form-control" %>

          <%= f.submit "Save changes", class: "btn btn-lg btn-info" %>

      <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
      <li><%= user.name %> Email: <%= user.email %>

    <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
    <% end %>
  <% end %>
  </li>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h2 class="text-center">Sign up</h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

          <%= f.label :name, class: "control-label" %>
          <%= f.text_field :name, :placeholder => " Enter your full name", 
                                      class: "form-control" %>

          <%= f.label :email, class: "control-label" %>
          <%= f.text_field :email, :placeholder => " Enter your email address", 
                                      class: "form-control" %>

          <%= f.label :password, class: "control-label" %>
          <%= f.password_field :password, :placeholder => " Enter your Password", 
                                      class: "form-control" %>

          <%= f.label :password_confirmation, "Confirmation", class: "control-label" %>
          <%= f.password_field :password_confirmation, :placeholder => " Confirm password", 
                                      class: "form-control" %>

          <%= f.submit "Create my account", class: "btn btn-lg btn-info" %>

      <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <section>
      <h2>Member Profile</h2>
      <h3><%= @user.name %></h3>
      <p>Email: <%= @user.email %></p>
      <%= link_to "Edit profile", edit_user_path(current_user) %>
    </section>
  </div>
</div>

app/views/welcome/_center.html.erb
<section>
  <div class ="dharmacenter">
    <div class = "dharmacenter-bkgd">
      <div class = "dharmacenter-overlay"></div>
    </div>
    <div class = "container">
      <h2 class="featurette-heading">A dharma center on Capital Hill. 
                                    <span class="text-muted">All are welcome.</span></h2>
      <p class="lead">A short walk from the Potomac Ave. Metro, we hold regular meditation and sadhana practice as well as a monthly Introduction to Tibetan Buddhism on the first Thursday. Visitors are encouraged and instructions are always provided.  <%= link_to 'Learn More &raquo;'.html_safe, about_path %></p>
    </div>
  </div>
</section>

app/views/welcome/_dharma.html.erb
<section class = "practice">
<div class = "container">
  <h2 class="text-center text-muted">Our Practices</h2>
  <div class="row practices">
    <div class = "col-md-8 col-md-offset-2">
      <div class="col-xs-4">
        <h4 class="text-center">Sunday</h4>
        <%= image_tag "med_buddha.png", :size => "150", :class => "featurette-image img-responsive img-circle"  %>

        <p class = "small text-center">Medicine Buddha and Amitabha</p>
        <p class = "small text-center">From 10 til 1 pm at the Dharma Center</p>
      </div><!-- /.col-xs-4 -->
      <div class="col-xs-4">
        <h4 class="text-center">Thursday</h4>

        <%= image_tag "mani.png", :size => "150", :class => "featurette-image img-responsive img-circle"  %>

        <p class = "small text-center">Chenrezig</p>
        <p class = "small text-center">From 7 til 8:30pm at the Dharma Center</p>
      </div><!-- /.col-xs-4 -->
      <div class="col-xs-4">
        <h4 class="text-center">Saturday</h4>  
               
        <%= image_tag "meditation.png", :size => "150", :class => "featurette-image img-responsive" %>

        <p class = "small text-center">Morning Mindfulness</p>
        <p class = "small text-center">From 10 til Noon at the Capitol Hill Presbyterian Church</p>
      </div><!-- /.col-xs-4 -->
    </div>
  </div><!-- /.row -->
</div>
</section>

app/views/welcome/_featurette.html.erb
<section class = "container teacher">
    <hr class="featurette-divider">
    <div class="row featurette">
             <!--  <h2 class = "text-center">Teachers</h2> -->
      <div class="col-md-3">

        <%= image_tag "rinpoche-lamarod.jpg", :size => "300", :class => "featurette-image img-responsive img-circle"  %>
      </div>
      <div class = "col-md-8">
        <h2 class="featurette-heading">Ven. Lama Norlha Rinpoche</h2>
        <p class = "lead">Lama Norlha Rinpoche, an accomplished meditation and retreat master, is the abbot of Kagyu Thubten Chöling Monastery and director of Kyabje Dorje Chang Kalu Rinpoche’s Dharma centers in the eastern United States. <%= link_to 'Read more &raquo;'.html_safe, about_path(anchor: "rinpoche") %></p>
        <div class = "row">
          <div class = "col-sm-12">
            <h3>Visiting Teachers</h3>
          </div>
        </div>

        <div class = "row">
          <div class = "col-xs-2">
            <%= image_tag "http://www.fillmurray.com/75/75", 
                :class => "featurette-image img-responsive img-circle"  %>
                <p class = "text-muted small">Lama Murray</p>
          </div>
          <div class = "col-xs-2">
            <%= image_tag "http://www.stevensegallery.com/75/75", 
                :class => "featurette-image img-responsive img-circle"  %>
                <p class = "text-muted small">Lama Segal</p>
          </div>
          <div class = "col-xs-2">      
            <%= image_tag "http://www.placecage.com/c/75/75", 
                :class => "featurette-image img-responsive img-circle"  %>
                <p class = "text-muted small">Lama Cage</p>
          </div>
        </div>
      </div>
    </div>
  <hr class="featurette-divider">
</section>

app/views/welcome/_teacher.html.erb
<section class = "container teacher">

    <div class="row featurette">
             <!--  <h2 class = "text-center">Teachers</h2> -->
      <div class="col-md-3">

        <%= image_tag "rinpoche-lamarod.jpg", :size => "300", :class => "featurette-image img-responsive img-circle"  %>
      </div>
      <div class = "col-md-8">
        <h2 class="featurette-heading text-muted">Ven. Lama Norlha Rinpoche</h2>
        <p class = "lead">Lama Norlha Rinpoche, an accomplished meditation and retreat master, is the abbot of Kagyu Thubten Chöling Monastery and director of Kyabje Dorje Chang Kalu Rinpoche’s Dharma centers in the eastern United States. <%= link_to 'Read more &raquo;'.html_safe, about_path(anchor: "rinpoche") %></p>
        <div class = "row">
          <div class = "col-sm-12">
            <h3 class="text-muted">Visiting Teachers</h3>
          </div>
        </div>

        <div class = "row">
          <div class = "col-xs-2">
            <%= image_tag "http://www.fillmurray.com/75/75", 
                :class => "featurette-image img-responsive img-circle"  %>
                <p class = "text-muted small">Lama Murray</p>
          </div>
          <div class = "col-xs-2">
            <%= image_tag "http://www.stevensegallery.com/75/75", 
                :class => "featurette-image img-responsive img-circle"  %>
                <p class = "text-muted small">Lama Segal</p>
          </div>
          <div class = "col-xs-2">      
            <%= image_tag "http://www.placecage.com/c/75/75", 
                :class => "featurette-image img-responsive img-circle"  %>
                <p class = "text-muted small">Lama Cage</p>
          </div>
        </div>
      </div>
    </div>
  <hr class="featurette-divider">
</section>

app/views/welcome/_test.html.erb
<section>
  <div class ="dharmacenter">
    <div class = "dharmacenter-bkgd">
      <div class = "dharmacenter-overlay"></div>
    </div>
    <div class = "container">
      <h2 class="featurette-heading">A dharma center on Capital Hill. 
                                    <span class="text-muted">All are welcome.</span></h2>
      <p class="lead">A short walk from the Potomac Ave. Metro, we hold regular meditation and sadhana practice as well as a monthly Introduction to Tibetan Buddhism on the first Thursday. Visitors are encouraged and instructions are always provided.  <%= link_to 'Learn More &raquo;'.html_safe, about_path %></p>
    </div>
  </div>
</section>

<section class = "practice">
<div class = "container">
  <div class="row practices">
    <div class = "col-md-8 col-md-offset-2">
      <div class="col-xs-4">
        <h4 class="text-center">Sunday</h4>
        <%= image_tag "med_buddha.png", :size => "150", :class => "featurette-image img-responsive img-circle"  %>

        <p class = "small text-center">Medicine Buddha and Amitabha</p>
      </div><!-- /.col-xs-4 -->
      <div class="col-xs-4">
        <h4 class="text-center">Thursday</h4>

        <%= image_tag "mani.png", :size => "150", :class => "featurette-image img-responsive img-circle"  %>

        <p class = "small text-center">Chenrezig</p>
      </div><!-- /.col-xs-4 -->
      <div class="col-xs-4">
        <h4 class="text-center">Saturday</h4>  
               
        <%= image_tag "meditation.png", :size => "150", :class => "featurette-image img-responsive" %>

        <p class = "small text-center">Morning Mindfulness</p>
      </div><!-- /.col-xs-4 -->
    </div>
  </div><!-- /.row -->
</div>
</section>